[package]
name = "bevy_pkv"
version = "0.3.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["Johan Helsing <johanhelsing@gmail.com>"]
description = "Persistent key value store for bevy"
keywords = ["gamedev", "key-value-store", "bevy"]
categories = ["game-development"]
repository = "https://github.com/johanhelsing/bevy_pkv"

[dependencies]
bevy = { version = "0.7", default-features = false }
sled = "0.34"
thiserror = "1.0"
bincode = "1.3"
serde = "1.0"

# todo wasm